name: matrix
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workshop: [dev-jammy, dev-noble]
    steps:
      - uses: actions/checkout@v6

      - uses: canonical/launch-workshop@v1
        with:
          workshop: ${{ matrix.workshop }}
          cache: |
            uv:cache

      - run: workshop run "$WS" unit-tests
        env:
          WS: ${{ matrix.workshop }}
